# Generated by Django 5.1.5 on 2025-01-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_filter',
            field=models.CharField(choices=[('tracks', 'Tracks'), ('events', 'Events'), ('races', 'Races'), ('drivers', 'Drivers'), ('cars', 'Cars')], default='normal', max_length=32),
        ),
    ]
