# Generated by Django 3.2.4 on 2025-01-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('australia', 'Australia'), ('italy', 'Italy'), ('united_kingdom', 'United_Kingdom'), ('america', 'America'), ('france', 'France'), ('spain', 'Spain'), ('monaco', 'Monaco'), ('canada', 'Canada'), ('netherlands', 'Netherlands'), ('mexico', 'Mexico')], max_length=32)),
                ('event_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('race_type', models.CharField(choices=[('race', 'Race'), ('sprint', 'Sprint')], max_length=30)),
                ('content', models.TextField(blank=True)),
                ('ticket_link', models.URLField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
