# Generated by Django 3.2.4 on 2025-01-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='country',
            field=models.CharField(choices=[('australia', 'Australia'), ('italy', 'Italy'), ('united_kingdom', 'United Kingdom'), ('america', 'America'), ('france', 'France'), ('spain', 'Spain'), ('monaco', 'Monaco'), ('canada', 'Canada'), ('netherlands', 'Netherlands'), ('mexico', 'Mexico')], max_length=32),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_link',
            field=models.URLField(blank=True),
        ),
    ]
